config/routes.rb
ActionController::Routing::Routes.draw do |map|
  

  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'
  map.resources :users

  map.resource :session

  map.my '/my', :controller => 'todos', :action => 'my'

  map.root :controller => 'todos', :action => 'my'

  map.resources :users do |users|
    users.resources :roles
  end

  map.resources :projects do |project|
   project.resources :tasks
  end

  map.resources :tasks 

  map.resources :projects do |project|
    project.resources :todos 
      
    
  end

  map.resources :todos do |todo|
    todo.resources :comments
  end
  
  

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :todos

end

app/models/role.rb
class Role < ActiveRecord::Base

  has_and_belongs_to_many :users

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :login_required, :harv_connect, :set_pagetitle
  
  
  def set_pagetitle
    @pagetitle = 'Working with projects'
  end

  def index
    @projects = @harvest.projects.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects.to_xml }
    end
  end

  def show
    @project = @harvest.projects.find(params[:id])
    @tasks = @project.tasks.find(:all)
    @tasks.each do |t|
      @task = @harvest.tasks.find(t.task_id)
      t.name = @task.name
    end
    @normal_tasks = @harvest.tasks.find(:all)
    @todos = Todo.find_all_by_project_id(@project.id)
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project.to_xml }
    end
  end

  def new
    @project = Project.new
    @clients = @harvest.clients.find(:all)

  end

  def edit
    @project = @harvest.projects.find(params[:id])
    @clients = @harvest.clients.find(:all)

  end

  def create
    @project = @harvest.projects.new
    #@clients = @harvest.clients.find(:all)
    
    @project.attributes = {:name => params[:project][:name],
                           :active => params[:project][:active],
                           :billable => params[:project][:billable],
                           :bill_by => params[:project][:bill_by],
                           :hourly_rate => params[:project][:hourly_rate],
                           :client_id => params[:project][:client_id],
                           :code => params[:project][:code],
                           :notes => params[:project][:notes],
                           :budget_by => params[:project][:budget_by],
                           :budget => params[:project][:budget],
                           :fees => params[:project][:fees]
                          }

    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully created.'
        format.html { redirect_to '/projects' }
        format.xml  { render :xml => @project, :status => :created }
      else
        flash[:error] = 'Error creating project.'
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = @harvest.projects.find(params[:id])
    
    @project.name = params[:harvest_resources_project][:name]
    @project.active = params[:harvest_resources_project][:active]
    @project.billable = params[:harvest_resources_project][:billable]
    @project.bill_by = params[:harvest_resources_project][:bill_by]
    @project.hourly_rate = params[:harvest_resources_project][:hourly_rate]
    @project.client_id = params[:harvest_resources_project][:client_id]
    @project.code = params[:harvest_resources_project][:code]
    @project.notes = params[:harvest_resources_project][:notes]
    @project.budget_by = params[:harvest_resources_project][:budget_by]
    @project.budget = params[:harvest_resources_project][:budget]
    @project.fees = params[:harvest_resources_project][:fees]
                           

    respond_to do |format|
      if @project.save
        flash[:notice] = 'Project was successfully updated.'
        format.html { redirect_to '/projects'}
        format.xml  { head :ok }
      else
        flash[:error] = 'Error updating project.'
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = @harvest.projects.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url}
      format.xml  { render :nothing => true }
    end
  end

  def activate
    @project = @harvest.projects.find(params[:id])
    respond_to do |format|
      if @project.toggle
        flash[:notice] = 'Project was successfully activated.'
        format.html { redirect_to '/projects'}
        format.xml  { head :ok }
      else
        flash[:error] = 'Error activating project.'
        format.html { redirect_to '/projects' }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Editing Project</h1>
<br />
PLEASE NOTE: features 'bill by', 'budget-by' must NOT be edited!

<% form_for @project, :url => { :action => "update" } do |f| %>
  <%= f.error_messages %>



 <p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :active %><br />
  <%= f.check_box :active %>
</p>
<p>
  <%= f.label :billable %><br />
  <%= f.check_box :billable %>
</p>
<p>
  <%= f.label :bill_by %><br />
  <%= f.text_field :bill_by %>
</p>
<p>
  <%= f.label :hourly_rate %><br />
  <%= f.text_field :hourly_rate %>
</p>
<p>
  <%= f.label :client_id %><br />
  <%= f.collection_select :client_id, @harvest.clients.find(:all), :id, :name, {}%>
</p>
<p>
  <%= f.label :code %><br />
  <%= f.text_field :code %>
</p>
<p>
  <%= f.label :notes %><br />
  <%= f.text_area :notes %>
</p>
<p>
  <%= f.label :budget_by %><br />
  <%= f.text_field :budget_by %>
</p>
<p>
  <%= f.label :budget %><br />
  <%= f.text_field :budget %>
</p>
<p>
  <%= f.label :fees %><br />
  <%= f.text_field :fees %>
</p>

<%= f.submit 'Update' %>
  
<% end %>

<%= link_to 'Show', :controller => 'projects', :action => 'show', :id => @project.id %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th>Billable</th>
    <th>Bill by</th>
    <th>Hourly rate</th>
    <th>Code</th>
    <th>Notes</th>
    <th>Budget by</th>
    <th>Budget</th>
    <th>Fees</th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%=h project.name %></td>
    <td><%=h project.active %></td>
    <td><%=h project.billable %></td>
    <td><%=h project.bill_by %></td>
    <td><%=h project.hourly_rate %></td>
    <td><%=h project.code %></td>
    <td><%=h project.notes %></td>
    <td><%=h project.budget_by %></td>
    <td><%=h project.budget %></td>
    <td><%=h project.fees %></td>
    <td><%= link_to 'Show',:controller => 'projects', :action => 'show', :id => project %></td>
    <td><%= link_to 'Edit', :controller => 'projects', :action => 'edit', :id => project  %></td>
    <td><%= link_to 'Destroy',  {:controller => 'projects', :action => 'destroy',:id => project}, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', :controller => 'projects', :action => 'new' %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<br />
PLEASE NOTE: features 'bill by', 'budget-by' must NOT be edited!


<% form_for @project, :url => { :action => "create" } do |f| %>
  <%= f.error_messages %>

 <p>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :active %><br />
  <%= f.check_box :active %>
</p>
<p>
  <%= f.label :billable %><br />
  <%= f.check_box :billable %>
</p>
<p>
  <%= f.label :bill_by %><br />
  <%= f.text_field :bill_by, :value => 'none' %>
</p>
<p>
  <%= f.label :hourly_rate %><br />
  <%= f.text_field :hourly_rate %>
</p>
<p>
  <%= f.label :client_id %><br />
  <%= f.collection_select :client_id, @harvest.clients.find(:all), :id, :name, {}%>

</p>
<p>
  <%= f.label :code %><br />
  <%= f.text_field :code %>
</p>
<p>
  <%= f.label :notes %><br />
  <%= f.text_area :notes %>
</p>
<p>
  <%= f.label :budget_by %><br />
  <%= f.text_field :budget_by, :value => 'none' %>
</p>
<p>
  <%= f.label :budget %><br />
  <%= f.text_field :budget %>
</p>
<p>
  <%= f.label :fees %><br />
  <%= f.text_field :fees %>
</p>

<%= f.submit 'Create' %>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <b>Project name:</b>
  <%=h @project.name %>
</p>
<p>
  <b>Active:</b>
  <%=h @project.active %>
</p>
<p>
  <b>Billable:</b>
  <%=h @project.billable %>
</p>
<p>
  <b>Bill by:</b>
  <%=h @project.bill_by %>
</p>
<p>
  <b>Hourly rate:</b>
  <%=h @project.hourly_rate %>
</p>
<p>
  <b>Code:</b>
  <%=h @project.code %>
</p>
<p>
  <b>Notes:</b>
  <%=h @project.notes %>
</p>
<p>
  <b>Budget by:</b>
  <%=h @project.budget_by %>
</p>
<p>
  <b>Budget:</b>
  <%=h @project.budget %>
</p>
<p>
  <b>Fees:</b>
  <%=h @project.fees %>
</p>

<br />
<%= link_to 'Edit', :controller => 'projects', :action => 'edit', :id => @project.id  %> |
<%= link_to 'Back', projects_path %>


<h2>Tasks for the Project:</h2>

<table>
  <tr>
    <th>Task name</th>
    <th>Billable</th>
    <th>Budget</th>
    <th>Deactivated</th>
    <th>Hourly rate</th>
    <th>Estimate</th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%=h task.name %></td>
    <td><%=h task.billable %></td>
    <td><%=h task.budget %></td>
    <td><%=h task.deactivated %></td>
    <td><%=h task.hourly_rate %></td>
    <td><%=h task.estimate %></td>
    <td><%= link_to 'Show',:controller => 'tasks', :action => 'show', :id => task %></td>
    <td><%= link_to 'Edit', :controller => 'tasks', :action => 'edit', :id => task  %></td>
    <td><%= link_to 'Destroy',  {:controller => 'tasks', :action => 'destroy',:id => task}, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', :controller => 'tasks', :action => 'new' %>

<h2>TODOs for the Project:</h2>

<table>
  <tr>
    <th>Todo title</th>
    <th>Description</th>
    <th>Due time</th>
    <th>Completed</th>
    
  </tr>

<% @todos.each do |todo| %>
    
  <tr>
    <td><%=h todo.title %></td>
    <td><%=h todo.description %></td>
    <td><%=h todo.due_time %></td>
    <td><%=h todo.completed %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, :confirm => 'Are you sure?', :method => :delete %></td>
    <td><%= link_to 'Complete', todo_path(todo, :todo => {:completed => true}), :method => :put%></td>
  </tr>
<% end %>
</table>
<br />
<h3>Create a New TODO</h3>

<% form_for:todo, :url => project_todos_path(:project_id => @project) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :due_time %><br />
    <%= f.datetime_select :due_time %>
  </p>
  <p>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </p>
  <p>
    Task: <br />

    <%= f.collection_select :task_id, @normal_tasks, :id, :name%>
  </p>
  
  <p>
    Assined to: <br />

    <%= f.collection_select :user_ids, User.find(:all, :order => 'login'), :id, :login, {}, :multiple => true %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>

<% end %>